VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IFakeDXUIEvent"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Sub Click(ByVal obj As clsFakeDXUI)
'
End Sub

Public Sub Unload(ByVal obj As clsFakeDXUI, ByRef Cancel As Boolean)
'
End Sub

Public Sub Change(ByVal obj As clsFakeDXUI)
'
End Sub

